# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 657ce9683274446857c171f8ae7e4457027d1cf73921d0418489d207d8cda22e6b297c2062f6563c56afca73419af8d44dcf5dba13badd284662e01f85af0cb2

test:
  secret_key_base: 7ac3a6e6dea693d0441758be1d395ef4cf379be9774ae5ff9d8cce1164d9206bb2326076e9716884bcefc0920dc03eeb4b20495ba45b9f842649da1cd7c731b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
